### ISSUE TITLE
New users of the program have to manually install libraries

### ISSUE THREAD

**Issue by Xenoxo** [Clockknight/album-downloader#4]
This is more a feature request....but I'm thinking there should be an easier way to run a python program that relies on a bunch of libraries that I don't have.

I had to manually run, get failed out, then install the library. Rinse and repeat until all libraries I didn't have were installed.

Maybe that *is* the way to do it?!

**Comment by Clockknight** [comment]
Planning on making this not a problem when I get an official release out. Looking into py2exe, but also should be able to include libraries in the repo for easier use
